### ISSUE TITLE
header image

### ISSUE THREAD

**Issue by ZMcGroarty** [TULiberalArts/Gender-Sexuality-and-Womens-Studies#13]
Hey,

Can we attempt to demo a new hero image for Heath? Im thinking it wont work (based on where the punch of the image is) but I wanted to test it either way. Can we try the original full size image first? Its attached here. I'll make a cropped version if it gets super wonky.  

![gsws_herofull-min](https://user-images.githubusercontent.com/15017242/51689217-3c771900-1fc4-11e9-8a35-e360a4773220.png)

**Comment by CVE82** [comment]
@ZMcGroarty ummmm I frigging love this hero! No problem at all I will pop the full size in now and see how it goes!...

**Comment by CVE82** [comment]
@ZMcGroarty yeahhh we will need a cropped version, the full layout only captures a quarter of his legs. Thanks dad!

**Comment by ZMcGroarty** [comment]
Lets try this one!

![hero_gsws2](https://user-images.githubusercontent.com/15017242/51988201-1a711100-2472-11e9-8df9-d36a1ebaa083.png)

**Comment by CVE82** [comment]
Trying now!

**Comment by CVE82** [comment]
Fabulous!
