### ISSUE TITLE
Landing page image/hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Gender-Sexuality-and-Womens-Studies#2]
Hero image just needs to be sized and placed, please and thank you.

**Comment by pixelyunicorn** [comment]
Pinging @ZMcGroarty, hero image can be found at http://github.com/TULiberalArts/Gender-Sexuality-and-Womens-Studies/blob/master/media/lgbtqflag.jpg

**Comment by ZMcGroarty** [comment]
rainbow flag translate awfully with red overlay -- lets pitch this

![hero_gsws-min](https://cloud.githubusercontent.com/assets/15017242/24208902/320274f0-0efb-11e7-8871-76dbb49affac.png)

**Comment by CVE82** [comment]
I agree, this is nice!
