### ISSUE TITLE
Faculty feed not pulling from Drupal

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Gender-Sexuality-and-Womens-Studies#4]
I checked the views in Drupal they are correct and restarted the build in Travis a couple of times and the faculty is still not pulling.

**Comment by pixelyunicorn** [comment]
The feed might not be set up yet, or the URL is wrong. Is https://liberalarts.temple.edu/profiles/gender-sexuality-and-womens-studies/csv correct?

**Comment by CVE82** [comment]
The url is correct I think the feed needs to be set up. Anyway we can do this and Liberal Studies today?

**Comment by tu-chill** [comment]
Drupal feed URLs do not include and.
