### ISSUE TITLE
Update header

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Gender-Sexuality-and-Womens-Studies#7]
Add punctuation so it reads: Gender, Sexuality, and Women's Studies (as constructed in the Bulletin)

**Comment by tu-chill** [comment]
![screen shot 2017-04-07 at 10 32 47 am](https://cloud.githubusercontent.com/assets/12816361/24804779/9753fbd8-1b7d-11e7-9908-ca00e4d9e754.png)

@zepstein  Also wondering if the first sentence should include the oxford comma - or whatever you want to call it?

**Comment by zepstein** [comment]
Hey @tu-chill, yes it should have the oxford comma, as that's how it's officially listed in the Bulletin. It should read as follows (include the apostrophe in "Women's): Gender, Sexuality, and Women's Studies

**Comment by zepstein** [comment]
the "a" in "and" in the header should be lowercase.
