### ISSUE TITLE
Add dashes to phone number in footer

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Gender-Sexuality-and-Womens-Studies#9]
215-204-1644

**Comment by tu-chill** [comment]
dashes can be edited in the _config.yml by anyone with access to repo
![screen shot 2017-04-07 at 10 36 03 am](https://cloud.githubusercontent.com/assets/12816361/24804973/33d7e578-1b7e-11e7-9351-a3d5163408cc.png)
